server:
  port: 8082

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;
    username: sa
    password: sa
  sql:
    init:
      data-locations: classpath:music.sql
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop

info:
  app:
    name: music-service
    description: Music Service created for Class 11
    version: 1.0.0
    server: