server:
  port: 8080
  
spring:
  cloud:
    gateway:
      routes:
        - id: gameRoute 
          uri: lb://games-service 
          predicates: 
            - Path=/games/**
        - id: libraryRoute 
          uri: lb://library-service 
          predicates: 
            - Path=/libraries/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
info:
  app:
    name: gateway-service
    description: Gateway Service created for Class 10
    version: 1.0.0