server:
  port: 8084

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1;
    username: sa
    password: sa
  sql:
    init:
      data-locations: classpath:library.sql
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
      
info:
  app:
    name: library-service
    description: Library Service created for Class 10
    version: 1.0.0