server:
  port: ${PORT:8080}

spring:
  cloud:
    gateway:
      default-filters:
        - name: CountFilter
      routes:
        - id: userRoute
          uri: http://localhost:8082/
          predicates:
            - Path=/users/**
          filters:
            - AddRequestHeader=user-request-header, testing-headers
            - AddResponseHeader=user-response-header, testing-response-header
        - id: productRoute
          uri: http://localhost:8085/
          predicates:
            - Path=/products/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
info:
  app:
    name: gateway-service
    description: Gateway Service created for Class 8
    version: 1.0.0
