server:
  port: 8080
  
spring:
  cloud:
    gateway:
      routes:
        - id: musicRoute 
          uri: lb://music-service 
          predicates: 
            - Path=/musics/**
        - id: playlistRoute 
          uri: lb://playlist-service 
          predicates: 
            - Path=/playlists/**

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
info:
  app:
    name: gateway-service
    description: Gateway Service created for Parcial
    version: 1.0.0
