eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
        
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info

info:
  app:
    name: image-service
    description: Image Service created for Class 6
    version: 1.0.0
